name: Test Python app
on:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pytest httpx pydantic pydantic-settings typing

    - name: Run Tests
      run: python -m pytest tests/